config/routes.rb
 Rails.application.routes.draw do

  root "parties#index"
  resources :characters
  resources :parties
  resources :character_parties, only: [:create, :new]

end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :parties, through: :character_parties
  has_many :character_parties
end

app/models/character_party.rb
class CharacterParty < ActiveRecord::Base
  belongs_to :character
  belongs_to :party
end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :characters, through: :character_parties
  has_many :character_parties
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/character_parties_controller.rb
class CharacterPartiesController < ApplicationController

  def new
    @party = CharacterParty.new
  end

  def create
    character_party = CharacterParty.create(character_party_params)

    if character_party.valid?
      redirect_to Party.find(character_party_params[:party_id])
    else
      render 'new'
    end
  end

  private

  def character_party_params
    params.require(:character_party).
      permit(:character_id, :party_id)

  end



end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end
  def show

    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def create
   @character = Character.new(character_params)
   @character.save
   redirect_to @character
  end

end

private

  def character_params
    params.require(:character).
      permit(:name, :hair_style, :level)
  end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def index
    @parties = Party.all
  end
  def show

    @party = Party.find(params[:id])
  end

  def new
    @party = Party.new
  end

  def create
    @party = Party.new(party_params)
    @party.save
    redirect_to @party
  end

end

private

  def party_params
    params.require(:party).
      permit(:name, :level)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/character_parties/new.html.erb
<h1> Character Parties </h1>

<%= form_for CharacterParty.new do |f| %>

    <%= f.label :character_id %>
    <%= f.collection_select :character_id, Character.all, :id, :name %>

    <%= f.label :party_id %>
    <%= f.collection_select :party_id, Party.all, :id, :name %>

    <%= f.submit %>

  <%  end %>

app/views/characters/index.html.erb
<% @characters.each do |c| %>

<p>
  <%= link_to c.name, character_path(c) %>
</p>

<%end%>

app/views/characters/new.html.erb
<h1> Creating New Character <h1>

<%= form_for Character.new do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :level %>
  <%= f.text_field :level %>

   <%= f.submit %>
   <% end %>

app/views/characters/show.html.erb
<h1><%= @character.name %></h1
<p><%= @character.level%></p>



<%= link_to "All Characters", characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rpg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parties/index.html.erb
<h1><%=pluralize(@parties.size, "Party") %></h1>

<% @parties.each do |party| %>
  <article>
    <header>
      <h2><%= link_to(party.name, party) %></h2>
    </header>
    <p>
      <%= party.style %>
    </p>
    <table>
      <tr>
        <th>Requirement</th>
        <td> Minimum Level Needed To Join <%= party.level %></td>
      </tr>
    </table>
  </article>
<% end %>

    Total Champions: <%= @character %>

    <p>

<%= link_to "new_Party",  new_party_path %>

<p>

  <%= link_to "All Characters", characters_path %>

  <p>

<%= link_to "New_Character", new_character_path %>

<p>

  <%= link_to "Form a Party", new_character_party_path %>

app/views/parties/new.html.erb
<h1> Creating New Party <h1>

<%= form_for Party.new do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :level %>
  <%= f.text_field :level %>

   <%= f.submit %>
   <% end %>

app/views/parties/show.html.erb
<h1><%= @party.name %> </h1>

  <article>
    <p>
      <%= @party.style %>
    </p>
    <table>
      <tr>
        <th>Requirement</th>
        <td> Minimum Level Needed To Join <%= @party.level %></td>
      </tr>
    </table>
  </article>

  <article>
    <p>
      Total Champions: <%= @party.characters.count %>

    </p>

    <% @party.characters.each do |c|%>
      <p><%= c.name %>
        <%end%>

      </p>

</article>

<%= link_to "All Parties", parties_path %>